# Generated by Django 4.2.7 on 2023-12-05 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Student: ')),
                ('phone', models.IntegerField(verbose_name='Phone Number: ')),
                ('age', models.IntegerField(verbose_name='Age: ')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulting',
                'verbose_name_plural': "Consulting's",
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='FAQ Title')),
                ('answer', models.TextField(verbose_name='FAQ Answer')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='RegisterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=588, verbose_name='Field Of Study')),
                ('name', models.CharField(max_length=20, verbose_name='Student Name')),
                ('phone_number', models.IntegerField(verbose_name='Student Phone Number')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=9), django.core.validators.MaxValueValidator(limit_value=30)])),
                ('status', models.BooleanField(default=False, verbose_name='Student Status')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Register Student',
                'verbose_name_plural': 'Register Students',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsor_image', verbose_name='Sponsor Image')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='VideoChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name Choice')),
                ('video', models.FileField(upload_to='video_choice_we', verbose_name='Video Choice')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Choice',
                'verbose_name_plural': 'Video Choices',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Mentor Name')),
                ('surname', models.CharField(max_length=25, verbose_name='Mentor Surname')),
                ('technology', models.CharField(max_length=50, verbose_name='Mentor Teach Technology')),
                ('image', models.ImageField(upload_to='gif_video_workers', verbose_name='Worker Gif Video')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
