# Generated by Django 4.2.3 on 2023-12-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image1',
            field=models.ImageField(default=1988, upload_to='hover_image_workers', verbose_name='Workers Hover Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(upload_to='image_workers', verbose_name='Workers Image'),
        ),
    ]
