# Generated by Django 4.2.7 on 2023-12-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_worker_image1_alter_worker_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField(verbose_name='OurVideo')),
            ],
        ),
    ]
